### ISSUE TITLE
Feature request: allow polyphonic input to the erase button so specific tracks can be erased

### ISSUE THREAD

**Issue by terrytheplatypus** [grough/lilac-loop-vcv#6]
I understand that this is supposed to be a very simple module, but given that the loop recording is polyphonic, it makes sense to be able to erase specific tracks instead of erasing the whole thing by providing polyphonic input to the erase button. I might try to develop this and submit a pull request.

**Comment by grough** [comment]
Hi @terrytheplatypus. Thanks for raising this issue. I agree that the erase control should comply with Rack's [voltage standards](https://vcvrack.com/manual/VoltageStandards#Polyphony):

> If monophonic … its voltage should be copied to all engines
> If polyphonic with enough channels … each channel voltage should be used in its respective engine
> If polyphonic but not enough channels … 0V should be copied to out-of-bounds engines

If you're interested in upgrading the erase control to work as above, a pull request would be most welcome. I'm happy to help test it and publish to the library if all goes well. If you're unable for any reason, I'd still hope to fix this myself at some point.

**Comment by terrytheplatypus** [comment]
I implemented this today, i'll clean it up a bit before i submit a pull request.

**Comment by terrytheplatypus** [comment]
I did have something working to erase the specific channels, but i realized there was a design aspect i didn't realize. My initial idea was that erasing the recording on every track should completely reset the loop. But I forgot that if you erase recording on one track, it'll still be recording on that track. So for example, if i'm recording on track A and B, and i erase A individually then B individually, there's no audio playing but the loop is still going. I wasn't sure if it would be better to keep the loop timer going in that case or stop the loop and reset the position and size to 0. If it's fine for the loop timer to still be going if the audio on all tracks is erased, then what i have is good enough. The user can still reset the loop by pressing the erase button.

**Comment by grough** [comment]
I think the least surprising behaviour in the case you described would be to reset the position and size to 0. It makes sense for the module to act consistently while in an "empty" state regardless of how it reached that state.

**Comment by terrytheplatypus** [comment]
I finished this feature, but I don't have permission to create a new branch for a pull request, i think. I could send you a diff.

**Comment by grough** [comment]
Glad to hear you got it working. If you fork this repository and push your changes to a branch on your fork, you should be able to use the "[compare across forks](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)" option create a pull request from your fork to the `main` branch on this repository.

**Comment by terrytheplatypus** [comment]
I did that now, sorry for the lack of understanding of github, i haven't used it in that way before.

**Comment by grough** [comment]
No problem and thanks for your contribution. I hope to test and review the code some time this week.

**Comment by terrytheplatypus** [comment]
did you get a chance to look over the pull request? i see there's a conflict now, but i dont understand why, because i was adding a separate method

**Comment by grough** [comment]
I ended up making some changes of my own to the code since you opened the pull request which caused a conflict. I think we should defer your polyphonic erase fix until I've finished some structural changes I'm making in support of a new more advanced looper module. I don't want to waste more of your time by asking you to resolve ongoing conflicts, so let me outline a plan and if you're still interested we can eventually get your stuff merged in.

1. I will finish restructuring the current looper code into a common module that can be used with the existing `LooperWidget` plus a more advanced new `LooperTwoWidget`
2. You could then apply the polyphonic erase fix to the new common module and test it out via `LooperTwoWidget` (the common module code will hopefully be better set up for modification)
3. The common code can then be used in both the original Looper module and the new "Looper Two" module (for lack of a better name)
4. One or both of the modules can then be published or at least shared for further testing

If you're happy to continue using your own fork of Looper to actually make music for now, I will continue with the restructuring work and post here when it's ready to be updated with your fix. Hopefully this makes sense. I'll attempt a better explanation once the new code structure is in place.

**Comment by grough** [comment]
@terrytheplatypus I left a [comment](https://github.com/grough/lilac-loop-vcv/pull/7#issuecomment-877322827) on your pull request. I have made some fairly large changes to the code, but it should still look familiar. If you want to continue your work you are more than welcome.

**Comment by grough** [comment]
Fixed in [v1.0.3](https://github.com/grough/lilac-loop-vcv/releases/tag/v1.0.3)
